; Patches applied during ESP-AT build for this product.

[support_ext_partition.patch]
    description = '[IDF-9560] Support to use partition table outside of the project directory'
    path = esp-idf
    dependency = AT_EXT_MODULE_CFG
